### ISSUE TITLE
Error in tester unit - cannot test boolean solver function

### ISSUE THREAD

**Issue by Not-Super-Nova** [Not-Super-Nova/ComputerScienceHelper#1]
Line 31 in TestForm.cs returns the following

```
System.InvalidCastException
  HResult=0x80004002
  Message=Specified cast is not valid.
  Source=BooleanAlgebraSolver
  StackTrace:
   at BooleanAlgebraSolver.TestForm.button2_Click(Object sender, EventArgs e) in C:\Users\Nova\source\repos\ComputerScienceHelper\BooleanAlgebraSolver\TestForm.cs:line 31
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at BooleanAlgebraSolver.Program.Main() in C:\Users\Nova\source\repos\ComputerScienceHelper\BooleanAlgebraSolver\Program.cs:line 19
```

**Comment by Not-Super-Nova** [comment]
Fixed in commit 772da037
